In [125]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [126]:
filename  ='cleaned_dataset.csv'
df = pd.read_csv(filename)
#df.select_dtypes(['object'])
#pour supprimer :  locality,
df['locality'].nunique()

5196

In [127]:
from sklearn.preprocessing import OrdinalEncoder

ordinal_encoder = OrdinalEncoder()
df['region_encoded'] = ordinal_encoder.fit_transform(df[['region']])


df.region_encoded.nunique()

3

In [128]:

df  = df.select_dtypes(include=['int64','float64'])
corr_matrix = df.corr()

# Extract the correlation values with 'price'
price_corr = corr_matrix['price']

# Sort the correlation values
sorted_price_corr = price_corr.sort_values(ascending=False)

sorted_price_corr


price               1.000000
bedroomcount        0.377297
kitchen             0.299656
roomcount           0.268313
swimmingpool        0.236449
stateofbuilding     0.228995
numberoffacades     0.225207
bathroomcount       0.197276
constructionyear    0.179481
surfaceofplot       0.128378
fireplace           0.101547
garden              0.072696
terrace             0.067950
livingarea          0.014218
propertyid          0.005533
toiletcount         0.004536
showercount         0.004457
furnished          -0.048302
postalcode         -0.083294
typeofproperty     -0.171074
region_encoded     -0.234643
monthlycharges           NaN
Name: price, dtype: float64

In [136]:

import seaborn as sns
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import mean_absolute_error

X = df[['livingarea', 'bedroomcount', 'kitchen', 'bathroomcount']]
y = df['price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=25)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_pred


mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
mean_absolute_error(y_test, y_pred)


95400.40954566929

In [130]:
#df.isnull().sum()
df.columns.duplicated()
df.duplicated().any()

False

In [131]:
#pd.get_dummies(df.region)
dew = df[['bedroomcount','price','constructionyear']]

dew.head()

bedroomcount   price  constructionyear
0             1   99000              1969
1            13  765000              1920
2             4  399000              2008
3             4  230000              1979
4             2  198000              1972

In [132]:
X = dew['price']
y= dew['bedroomcount']
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size=0.4,random_state=23)



In [133]:
X_train

49557    300000
41256    164000
15244    225000
55688    380000
19138     80000
          ...  
71711    493350
9704     255000
76726    339000
92105    499374
9256     480000
Name: price, Length: 56934, dtype: int64

In [134]:
X_train = np.array(X_train)

X_test = np.array(X_test)
lr=LinearRegression()


In [135]:
lr.fit(X_train,y_train)

ValueError: Expected 2D array, got 1D array instead:
array=[300000 164000 225000 ... 339000 499374 480000].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [ ]:
c = lr.intercept_

m = lr.coef_
m

array([3.37907442e-06])

In [ ]:
Y_pred_train = m*X_train+c
Y_pred_train

array([[2.48770096],
       [2.02814684],
       [2.23427038],
       ...,
       [2.61948486],
       [3.16140055],
       [3.09593436]])

In [ ]:
lr.predict(X_train)


array([2.48770096, 2.02814684, 2.23427038, ..., 2.61948486, 3.16140055,
       3.09593436])